### ISSUE TITLE
I21_importing a clean copy of ThirdPersonBP to the project

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#21]
I was working on my branch, trying to attach the tool to character, and it turns out that original  ThirdPersonBP has been turn into Third Person Character ( then one with integrated camera ) and second copy has the AI attached to it, hence working with it is kind of impossible as when added to scene it imminently following the node. 

I tried to export clean copy of ThirdPersonCharacter from a new 3rd person project, and place it in Content folder of my project, but that didn't work.

 So the question is, can I just duplicate AI_Ant and then remove any extra blue prints from it ?

**Comment by BojanStankovic** [comment]
Hi @napiorek,

Let's try to keep things organised as they were. First of all, there is no need for creating a new issue if it is related to an issue already opened. In this case you should write this comment under #20 since it is part of it.
Secondly, if you are working on a new issue you are supposed to create a branch for that issue. Also, the branches belong to issues not the people who are working on the issue. It is possible to have more than one person work on an issue therefore on a specific branch as well.

Could you please post this in a related issue and mark this one as duplicate and close it down. Any further discussion regarding this problem should continue in #20

**Comment by napiorek** [comment]
Ok, sorry for confusion.

**Comment by rbakerusw** [comment]
Duplicate issue.
