### ISSUE TITLE
Crosshair

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#29]
I noticed that highlighting the ants can be quite difficult since we don't have a crosshair. The user has to try and line up the ant in the centre of the screen and click. This can be a bit frustrating since it is easy to miss so I am suggesting we have a crosshair in the middle of the screen allowing the user to aim at the ant they want to.

**Comment by BojanStankovic** [comment]
Yes! That is one of the things we should implement for the first build. Here is a link to a tutorial that helps with implementing a basic crosshair: https://www.youtube.com/watch?v=3o_cEnmKL2g

Eventually it would be nice if we manage to modify it so that the crosshair itself adopts to the geometry of the object beneath it. Consider this an icing for the cake.

**Comment by ghost** [comment]
Sounds like a good idea to me guys, It'll make the game feel more intuitive for the player.

**Comment by rbakerusw** [comment]
Ok thanks for linking the tutorial, I will look into it now and start working on the crosshair.

**Comment by rbakerusw** [comment]
I have now added a simple crosshair to the game so the player can now accurately click on ants. The crosshair is static so it doesnt react to the geometry but we can try to add that at a later date.

**Comment by BojanStankovic** [comment]
It looks good enough for the first build. Going to merge it to the develop now

**Comment by BojanStankovic** [comment]
Merged. Closing
