### ISSUE TITLE
First spawning ant will run in opposite direction

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#48]
The first ant coming out of the spawner will always run in the opposite direction set on the spawner.

**Comment by BojanStankovic** [comment]
Sometimes two ants run into the opposite direction. Have you tried increasing the interval between the 2 spawns?

**Comment by napiorek** [comment]
Ryan (@rbakerusw)found out that placing the wall just behind spawner or directional node underneath the spawner seems to solve the issue. 
If we all agree that this is a acceptable solution, then we can consider this problem as solved.

**Comment by BojanStankovic** [comment]
I would suggest that instead of a wall we use one of the directional nodes as a part of the spawn box. This will look nicer and it will be placed on the scene together with the spawn box

**Comment by elliotnaylor** [comment]
This is a fair and easy method and won't even need a push.

**Comment by elliotnaylor** [comment]
Peter just tested this while making an ant and it's not a suitable method, i'll work on it now

**Comment by rbakerusw** [comment]
Why is it not a suitable method? What was wrong?

**Comment by elliotnaylor** [comment]
Spawning inside the box doesn't count as collision.  So it would have to fall onto it or something, i'm looking into why the first ant is being strange

**Comment by BojanStankovic** [comment]
I have fixed this by adding four walls as a part of the spawner object. The walls are not visible but they do detect collision depending on the direction set in the spawner. This can be a solution for this one so we can focus on other things.

Someone should review so we can merge and close it

**Comment by napiorek** [comment]
Tested and could not found anything wrong except one minor thing.
First two ants are closer than the rest of ants, and I suspect this is because first ant going in opposite direction and bounce off the invisible wall.

![image](https://cloud.githubusercontent.com/assets/22525895/24071279/39d5f1da-0bc6-11e7-9529-4af48009e6e3.png)

Any way, well done on solving this issue @BojanStankovic

**Comment by BojanStankovic** [comment]
That is right, the first two ants are closer together because the first one collides with the wall first and then changes the direction to a correct one. That's how we had it with the additional cube object placed next to spawner. Maybe we could fine tune it so the walls are closer to the spawning position so the gap should be closer to the supposed one. For now this will do.

Merged. Closing
