### ISSUE TITLE
Movement/scaling discussion

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#5]
We need to decide on the best way to move the map while focusing on VR and normal PC.  Both will use completely different methods.

We've spoken about tp points and using the "walk around" with HTC vive, which we could actually use together.  While we haven't really discussed what we'd do with normal PC users.  Would we have a character model you'd move around to stick with the theme, or would we have a camera that the user moves freely?

I'd also like to mention the scaling between the player and the "ants".  How big should they be in comparison to the player?

We're just lacking on detail at the moment that i'd like to polish before making the game.

**Comment by rbakerusw** [comment]
Potentially, we could still use the teleport method or something for normal PC users but obviously it wont feel as immersive as it would in VR (but i suppose that is why we are using VR). We could possible use the same method we use for VR and change it if we have time at the end of the project or something.

As for the scaling with the ants, I'm not sure. Maybe we could have some sort of scaling option so you can zoom in and out depending on how you would prefer it. Similar to other sort of strategy games where you can see the whole map or a specific area in much more detail.

**Comment by BojanStankovic** [comment]
Well, polishing a detail before making some kind of actual environment might prove a bit challenging. I would suggest creating a prototype again here and develop the game and features as we go. No point in perfecting something that doesn't exist.

Now, regarding the issues you are mentioning, Ryan pretty much sums it up. Without VR we can still use the same control mechanics, but when using VR a player can feel the immersion. If we have enough time later on (which I doubt we will have considering we still don't have anything) we can think about implementing a different mechanics for non-VR version. Just keep in mind that every software project is developed and improved as it goes instead of having everything figured out and than making it.

Also, lets aim to develop for Oculus since not all headsets have space tracking available at the moment.

**Comment by BojanStankovic** [comment]
Not an issue at the moment. Closing
