### ISSUE TITLE
Compilation warning on the Kamikaze node

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#56]
The Kamikaze macro node is producing a warning when compiling a ThirdPersonCharacter. This needs to be solved by the 2nd build

**Comment by rbakerusw** [comment]
I will try to look into solving this.

Edit: I just downloaded the latest version and I'm not seeing the error. Do you know how to recreate this error?

**Comment by rbakerusw** [comment]
I just looked at the network graph realized that the compiling error is on I41_Attaching_Tool_To_Ant

Edit: nevermind it is on the develop branch

As discussed with Elliot the error is due to a triggerbox but the trigger box is going to be removed in the latest version anyway so this does need to be fixed.

**Comment by elliotnaylor** [comment]
The error is caused because it's referring to the out of bounds box that doesn't exist.  This will no longer be an issue when #55 is merged.  Closing branch

**Comment by BojanStankovic** [comment]
This is not merged into the develop and therefore it has no place in the closed issues. As a result, a duplicate issue is opened by Richard.

Please don't close issues that haven be resolved.
