### ISSUE TITLE
Bug Report: Level Timer

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#59]
The level’s timer isn’t currently taking a value from each level, a variable should to be created in the level blueprint to store this value and every second this value needs to be decremented by 1 second.

If the timer reaches zero the game should be exited, this counts as a secondary end game condition.

**Comment by ghost** [comment]
This issue has been resolved, the macros and “ants_needed” variable needs to be present in every level blueprint otherwise the timer won’t work as designed.

**Comment by BojanStankovic** [comment]
This had two minor things needed fixing. One was that the modifications done inside the level blueprint were done using level's internal macros so I recreated this using the macro libraries like we have done everything else. The other thing is that I connected the timer runs out event to the End Game screen instead of game exiting on it's own.

Merged. Closing
